### ISSUE TITLE
NavigationBarItem displayed incorrectly

### ISSUE THREAD

**Issue by Moiudev** [BharadwajRns/BottomNavigationCompose#1]
When **Profile** is selected and then the Back button is pressed, the screen returns to **HomeScreen**, but the **NavigationBarItem-Home** is not selected, and the **NavigationBarItem-Profile** is still selected.

**Comment by BharadwajRns** [comment]
Hey there! sorry for your inconvenience I just made a push to the repo that fix your problem check that out.
